### ISSUE TITLE
Redesign logo to reflect goals of the organisation

### ISSUE THREAD

**Issue by michaelbarton** [bioboxes/logo#2]
@kbradnam made several useful suggestions in bioboxes/rfc#40 concerning the logo of the organisation. Specifically that the current logo should reflect the aims of the organisation. I will move that discussion to the logo repo.

**Comment by michaelbarton** [comment]
The current logo looks as follows:

![Current bioboxes logo](https://raw.githubusercontent.com/bioboxes/logo/33f86500e06b1afc741d58c12e5ba165da1e69df/logo.png)

**Comment by michaelbarton** [comment]
@kbradam suggested the following logo to more accurately reflect there are boxes and this is related to biology.

![Keith's logo suggestion](https://cloud.githubusercontent.com/assets/2367600/6031895/f6ec6b3a-abb7-11e4-93fb-04d7883f0ea8.png)

**Comment by michaelbarton** [comment]
I have tried to incorporate these suggestions and update the logo further

![monochrome logo](https://raw.githubusercontent.com/bioboxes/logo/redesign/monochrome-materials/logo.png)

**Comment by michaelbarton** [comment]
I also made a similar colour version too

![colour version of logo](https://raw.githubusercontent.com/bioboxes/logo/redesign/color-materials/logo.png)

**Comment by michaelbarton** [comment]
Ignore the edges of these, I forgot to set the transparency when exporting the image.

**Comment by michaelbarton** [comment]
Here is also a version where the boxes are side by side

![side by side logo](https://raw.githubusercontent.com/bioboxes/logo/redesign/side-by-side/logo.png)

**Comment by kbradnam** [comment]
I like the different weights of the fonts and prefer the last design the most, perhaps because in the previous designs, too much of the kog icon is obscured by the DNA box.

It's worth looking at this at smaller sizes to see how recognizable each element is. When I have the image as file on my (Mac) desktop I can just read the text ('bio' is a bit hard to see) and sort of make out the icons. Maybe the spacing between each box could be increased a bit?

**Comment by michaelbarton** [comment]
I have tried a slightly different approach using 3D boxes incorporating
elements of the previous designs. I think this has the advantage that the left
hand side could be used for small icons, such as twitter. This could solve the
problem @kbradnam mentioned where the writing may not be visible at small
sizes.

![3D logo](https://raw.githubusercontent.com/bioboxes/logo/redesign/3d-boxes/logo.png)

**Comment by michaelbarton** [comment]
I will merge the branch containing this last logo version. Any further suggestions are welcome and this issue can be reopened.

**Comment by michaelbarton** [comment]
Merged in PR #3
